var Config = Config || {};

Config.whitelist = [
	// general sites
	'wikipedia\\.org',
	'wikimedia\\.org',
	'wiktionary\\.org',
	'github\\.com',
	'reddit\\.com',
	'gamefaqs\\.com',
	'facebook\\.com',
	'fbcdn\\.net',
	'twitter\\.com',
	'deviantart\\.com',
	'youtube\\.com',
	'youtu\\.be',
	'zombo\\.com',
	'strawpoll\\.me',
	'twitch\\.tv',
	'take-a-screenshot\\.org',

	// pokemon sites
	'pokemonshowdown\\.com',
	'psim\\.us',
	'smogon\\.com',
	'upokecenter\\.com',
	'veekun\\.com',
	'bulbagarden\\.net',
	'serebii\\.net',
	'nuggetbridge\\.com',
	'pokecommunity\\.com',
	'pokemon-online\\.eu',
	'pokemonlab\\.com',
	'shoddybattle\\.com',
	'pokemonxy\\.com',
	'pokemon\\.com',
	'pokecheck\\.org',

	// personal sites
	'breakdown\\.forumotion\\.com',
	'frostserver\\.net',
	'thebattletower\\.no-ip\\.org',
	'meltsner\\.com',
	'guangcongluo\\.com',
	'cathyjf\\.com',
	'xiaotai\\.org',

	// text
	'pastebin\\.com',
	'hastebin\\.com',
	'trello\\.com',
	'challonge\\.com',
	'piratepad\\.net',
	'4chan\\.org',

	// images
	'd\\.pr',
	'snag\\.gy',
	'gyazo\\.com',
	'imgur\\.com',
	'4cdn\\.org'
];

Config.customcolors = {
	'theimmortal': 'taco',
	'bmelts': 'testmelts',
	'zarel': 'aeo',
	'zarell': 'aeo',
	'greatsage': 'test454',
	'snowflakes': 'snowflake',
	'jumpluff': 'zacchaeus',
	'zacchaeus': 'jumpluff',
	'kraw': 'kraw1',
	'growlithe': 'steamroll',
	'snowflakes': 'endedinariot',
	'doomvendingmachine': 'theimmortal',
	'mikel': 'mikkel',
	'arcticblast': 'rsem',
	'mjb': 'thefourthchaser',
	'thefourthchaser': 'mjb',
	'tfc': 'mjb',
	'mikedecishere': 'mikedec3boobs',
	'heartsonfire': 'haatsuonfaiyaa',
	'royalty': 'wonder9',
	'osiris': 'yamraiha',
	'limi': 'azure2',
	'haunter': 'cathy',
	'ginganinja': 'piratesandninjas',
	'aurora': 'c6n6fek',
	'jdarden': 'danielcross',
	'solace': 'amorlan',
	'dcae': 'galvatron',
	'queenofrandoms': 'hahaqor',
	'jelandee': 'thejelandee',
	'diatom': 'dledledlewhooop',
	'waterbomb': 'wb0',
	'texascloverleaf': 'aggronsmash',
	'treecko': 'treecko56',
	'treecko37': 'treecko56',
	'violatic': 'violatic92',
	'exeggutor': 'ironmanatee',
	'ironmanatee': 'exeggutor',
	'shamethat': 'aaa10',
	'skylight': 'aerithass',
	'prem': 'premisapieceofshit',
	'goddessbriyella': 'alyca',
	'nekonay': 'catbot20',
	'coronis': 'kowonis',
	'vaxter': 'anvaxter',
	'mattl': 'mattl34',
	'shaymin': 'test33',
	'orphic': 'dmt6922',
	'kayo': 'endedinariot',
	'tgmd': 'greatmightydoom',
	'vacate': 'vaat111111111',
	'cathy': {color: '#ff5cb6'}
};
